### ISSUE TITLE
the problem with deploy.prototxt( Unknown bottom blob 'label')

### ISSUE THREAD

**Issue by bugumemeda** [wy1iu/LargeMargin_Softmax_Loss#11]
I have trained a models with LargeMargin_softmax_loss and want deploy it to new data without label.But the LargeMarginInnerProduct layer needs to input label. I have tried use InnerProduct layer instead of it, but it occur  target_blobs.size() == source_layer.blobs_size() (2 vs. 1).This means the weigths can't copy from  LargeMarginInnerProduct layer to  InnerProduct layer.
Now, I have no idea to use the model in new data without label. What should I do to counter the problem?Can you share you deploy.prototxt?
Thank you!

**Comment by luoyetx** [comment]
LargeMarginInnerProduct layer doesn't have bias, set `bias_term: false` in InnerProduct layer in your prototxt

**Comment by bugumemeda** [comment]
@luoyetx I solved the ploblem by setting bias_term: false. Thank you very much.

**Comment by wy1iu** [comment]
Sorry about that. I will release the deploy file next time.

**Comment by cocowf** [comment]
How about the deploy file ? @wy1iu @luoyetx @chunyanlian
