### ISSUE TITLE
Why this particular construction?

### ISSUE THREAD

**Issue by bkj** [wy1iu/LargeMargin_Softmax_Loss#13]
Hi -- 

I was wondering where you got the idea for the specific construction of the L-softmax.  It seems like maybe you could achieve a similar goal by enforcing a margin like 

`norm(W) * norm(x) * (m * cos(theta) - m + 1)` 

instead of 

`norm(W) * norm(x) * cos(m * theta)`

as you do in the paper.

The former seems simpler because you don't have to worry about constructing a `psi` function that behaves well for all values of `theta`,  `m` doesn't have to be integer valued, etc. Also, in the paper, the gradient of `psi` is 0 at `pi/2`, which AFAICT is an undesirable side effect of the choice of `psi`.  Is that right, or is there some reason that `grad psi(pi/2)` should be 0?  

The proposed alternative above would have the same shape as `cos` in `[0, pi]` but with a range of `[-m, 1]`, which seems maybe more natural.

Thoughts?  Am I missing something?  Did you try this and it stunk in practice?  

Thanks

**Comment by wy1iu** [comment]
The one you proposed may work, and I indeed tried it. The reason I have not used it is because the intuition is different. If you did not multiply m to the \theta, it will lose some of the angular intuition. But in practice, it could work.

**Comment by bkj** [comment]
Ok thanks -- makes sense.  Do you have any thoughts about the saddle point at `pi/2`?  Is there a reason why that might be desirable, or am I right that it's just a side effect of your choice of `psi`?

**Comment by wy1iu** [comment]
That is exactly what lambda is used for.
