### ISSUE TITLE
hard to convergence

### ISSUE THREAD

**Issue by auroua** [wy1iu/LargeMargin_Softmax_Loss#14]
I have reimplemented L_softmax using tensorflow, but I found it  really hard to convergence.

**Comment by wy1iu** [comment]
Please pay attention to the note I wrote. Try to adjust lambda and change ReLU to PReLU. From my experience, PReLU converges better.

**Comment by nrupatunga** [comment]
In the paper it is mentioned it is hard to converge for dataset with larger number of classes. 

![image](https://user-images.githubusercontent.com/980580/61459744-0f139280-a98b-11e9-9323-58946d73bee1.png)

Any explanation on why the convergence is hard to achieve. ? 
Thanks in advance.

**Comment by auroua** [comment]
I think the

albert_wei

**Comment by nrupatunga** [comment]
@auroua I didn't get you?
