### ISSUE TITLE
some typos in

### ISSUE THREAD

**Issue by kli-nlpr** [wy1iu/LargeMargin_Softmax_Loss#16]

**Comment by kli-nlpr** [comment]
![qq 20170525163143](https://cloud.githubusercontent.com/assets/13194870/26442577/b41802cc-4167-11e7-9fc1-018e7497759f.jpg)
![qq 20170525163202](https://cloud.githubusercontent.com/assets/13194870/26442579/b44b3e12-4167-11e7-95aa-88ac495e8ea9.jpg)

**Comment by wy1iu** [comment]
Thanks for pointing them out.
