### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by 1nFl4me2** [wy1iu/LargeMargin_Softmax_Loss#17]
Hi,

What license are the largemargin_inner_product layers released under?

Can i use your implementation to train models for commercial use? Or do i have to implement it myself before training commercial models?

Thanks.

**Comment by wy1iu** [comment]
It has already been mentioned in README.

**Comment by 1nFl4me2** [comment]
Hi,

I am just confused because you added an MIT license which permits commercial use but then added a disclaimer that it can only be used for research purposes.

Thanks.

**Comment by wy1iu** [comment]
You just need to follow the MIT license.
