### ISSUE TITLE
Computation of k value from eq. (6)

### ISSUE THREAD

**Issue by MaggiePas** [wy1iu/LargeMargin_Softmax_Loss#19]
Hello and thank you for the code and the awesome paper!

I haven't fully understood how you compute the value of k from the Equation (6) in the paper. Could you please provide some small explanation?
I have followed luoyetx implementation for the computation of k for mxnet but in most cases I get k=0, even for m>1 in MNIST and I think that potentially it's a problem that does not allow my implementation in tensorflow to reach the high accuracy you have.

Thanks a lot in advance,
Magda

**Comment by wy1iu** [comment]
k decides which range \phi(\theta) is in. It is simply a formulation for the multi-range function \phi(\theta).
Also, it is okay for k to be 0. In fact, if m=1, k can only be 0.

**Comment by yxchng** [comment]
@MaggiePas have you figured out? I am trying to decipher where this code compute k too
