### ISSUE TITLE
Why lambda_min not used in Backward?

### ISSUE THREAD

**Issue by luoyetx** [wy1iu/LargeMargin_Softmax_Loss#2]
As the title described. In forward part, lambda won't be smaller than lambda_min, but in backward part, it doesn't compare with lambda_min. Is there a reason to do so or just a mistake ?

**Comment by wy1iu** [comment]
There is no need to compare lambda in back prop. If lambda reaches lambda_min, it will stay unchanged during the rest of the optimization.

**Comment by luoyetx** [comment]
then, I think this [line](https://github.com/wy1iu/LargeMargin_Softmax_Loss/blob/master/src/caffe/layers/largemargin_inner_product_layer.cu#L410) and this [line](https://github.com/wy1iu/LargeMargin_Softmax_Loss/blob/master/src/caffe/layers/largemargin_inner_product_layer.cpp#L272) won't promise. Since `iter_` is always increased by 1 during forward, `lambda` will be smaller than `lambda_min`. Right?

**Comment by wy1iu** [comment]
Yes, you are right about this. My apologies. It seems like I commit an old version of my code. Without lambda_min, it is okay for MNIST and CIFAR10, which is the reason I did not find out this mistake. But in the implementation for LFW and CIFAR100, these lines has been deleted. You will need lambda_min to reproduce performance in LFW and CIFAR100. Really sorry about that. I will fix this bug now.

**Comment by wy1iu** [comment]
Thanks very much for reporting the bug. Really appreciate it.  :)
