### ISSUE TITLE
The difference between the bn_layer.cpp and  bnll.cpp

### ISSUE THREAD

**Issue by PkuRainBow** [wy1iu/LargeMargin_Softmax_Loss#7]
I notice that you use the BN layer implemented by yourself, could you share me the different between them ?

**Comment by wy1iu** [comment]
It follows the original BN paper's implementation.

**Comment by runauto** [comment]
@wy1iu ，I find the "bn_layer" is different between the bn_layer.cpp and cudnn_bn_layer.cpp，the result different，when i use gpu mode in test ， the result is right，but  use cpu mode in test ,the result is error.
