### ISSUE TITLE
how to test with input data,there is a problem with bottom: "label"

### ISSUE THREAD

**Issue by xqpinitial** [wy1iu/LargeMargin_Softmax_Loss#9]
when i want to write deploy.prototxt,
the input is :
input: "data"
input_dim: 25
input_dim: 3
input_dim: 224
input_dim: 224

However ,
layer {
  name: "fc8"
  type: "LargeMarginInnerProduct"
  bottom: "fc7"
  bottom: "label"
  top: "fc8"
  top: "lambda"
  param {
    name: "fc8"
    lr_mult: 0
  }
  largemargin_inner_product_param {
    num_output: 100
    type: SINGLE
    base: 0
    gamma: 1
    iteration: 0
    lambda_min: 0
    weight_filler {
      type: "msra"
    }
  }
  include {
    phase: TEST
  }
}
there is a error :+1:  bottom: "label"
how to input bottom: "label"

**Comment by mnikitin** [comment]
Hi!

You should use SoftmaxWithLoss layer after your (LargeMargin)InnerProduct. And in that loss layer you should specify as bottoms "fc8" and "label" blobs.

**Comment by xqpinitial** [comment]
@mnikitin @wy1iu I don't given a clear count. I want to get the properity of every num of output.
the input is 

input: "data"
input_dim: 25
input_dim: 3
input_dim: 224
input_dim: 224

when using "LargeMarginInnerProduct", the label is must used,where to input lavel.

**Comment by cocowf** [comment]
Hi have you solved this problem? the same as you @xqpinitial
